var TILE_WALL = 'W';
var TILE_FLOOR = 'F';
var TILE_HERO = 'H';
var TILE_ENEMY = 'E';
var TILE_WEAPON = 'S';
var TILE_POTION = 'P';
var TILE_EMPTY = 'empty-tile'

var MAP_WIDTH = 40;
var MAP_HEIGHT = 24;

var HERO_MAX_HEALTH = 100;
var ENEMY_MAX_HEALTH = 50;
var HERO_BASE_ATTACK = 25;
var ENEMY_BASE_ATTACK = 15;

var POTION_IMPROVEMENTS = 25;
var WEAPON_IMPROVEMENTS = 15;


var ENEMY_ATTACK_INTERVAL = 1000
var ENEMY_MOVEMENT_INTERVAL = 1000;

var MAX_COUNT_ENEMIES = 10;
var MAX_COUNT_POTIONS = 10;
var COUNT_WEAPONS = 2;